DROP TABLE IF EXISTS bad_choice CASCADE;
DROP TABLE IF EXISTS good_choice CASCADE;
DROP TABLE IF EXISTS step CASCADE;
DROP TABLE IF EXISTS quest CASCADE;
DROP TABLE IF EXISTS user_quest CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS quest
(
    quest_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quest_name VARCHAR(512) UNIQUE NOT NULL,
    description VARCHAR(1000) NOT NULL,
    img VARCHAR(256),
    CONSTRAINT pk_quest PRIMARY KEY (quest_id)
);

CREATE TABLE IF NOT EXISTS step
(
    step_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question VARCHAR(1000) NOT NULL,
    img VARCHAR(256),
    quest_id INT NOT NULL,
    is_start BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT pk_step PRIMARY KEY (step_id),
    FOREIGN KEY (quest_id) REFERENCES quest (quest_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS choice
(
    choice_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    answer VARCHAR(1000) NOT NULL,
    state VARCHAR(64) NOT NULL,
    current_step_id INT NOT NULL,
    CONSTRAINT pk_choice PRIMARY KEY (choice_id),
    FOREIGN KEY (current_step_id) REFERENCES step (step_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS the_end
(
    the_end_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    choice_id INT NOT NULL,
    text VARCHAR(1000) NOT NULL,
    CONSTRAINT pk_the_end PRIMARY KEY (the_end_id),
    FOREIGN KEY (choice_id) REFERENCES choice (choice_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS to_be_continue
(
    choice_id INT NOT NULL,
    step_id INT NOT NULL,
    FOREIGN KEY (choice_id) REFERENCES choice (choice_id) ON DELETE CASCADE,
    FOREIGN KEY (step_id) REFERENCES step (step_id) ON DELETE CASCADE
);

INSERT INTO quest (quest_name, description)
VALUES ('Quest one', 'Some description');

INSERT INTO step (question, quest_id, is_start)
VALUES ('You''ve lost your memory. Accept the UFO challenge?', 1, true);
INSERT INTO step (question, quest_id)
VALUES ('You accepted the challenge. Going up to the bridge to the captain?', 1);
INSERT INTO step (question, quest_id)
VALUES ('You went up to the bridge. Who are you?', 1);

INSERT INTO choice (answer, state, current_step_id)
VALUES ('Reject a call', 'FAILURE', 1);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Refuse to go up to the bridge', 'FAILURE', 2);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Lie about yourself', 'FAILURE', 3);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Take the challenge', 'CONTINUE', 1);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Climb to the bridge', 'CONTINUE', 2);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Tell the truth about yourself', 'WIN', 3);

INSERT INTO the_end (choice_id, text)
VALUES (1, 'You declined the call');
INSERT INTO the_end (choice_id, text)
VALUES (2, 'You didn''t negotiate');
INSERT INTO the_end (choice_id, text)
VALUES (3, 'Your lies have been exposed');
INSERT INTO the_end (choice_id, text)
VALUES (6, 'You declined the call');

INSERT INTO to_be_continue (choice_id, step_id)
VALUES (4, 2);
INSERT INTO to_be_continue (choice_id, step_id)
VALUES (5, 3);

INSERT INTO quest (quest_name, description)
VALUES ('Quest two', 'Very strange quest');

INSERT INTO step (question, quest_id, is_start)
VALUES ('You''ve lost your memory. Accept the UFO challenge?', 2, true);
INSERT INTO step (question, quest_id)
VALUES ('You accepted the challenge. Going up to the bridge to the captain?', 2);
INSERT INTO step (question, quest_id)
VALUES ('You went up to the bridge. Who are you?', 2);

INSERT INTO choice (answer, state, current_step_id)
VALUES ('Reject a call', 'FAILURE', 4);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Refuse to go up to the bridge', 'FAILURE', 5);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Lie about yourself', 'FAILURE', 6);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Take the challenge', 'CONTINUE', 4);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Climb to the bridge', 'CONTINUE', 5);
INSERT INTO choice (answer, state, current_step_id)
VALUES ('Tell the truth about yourself', 'WIN', 6);

INSERT INTO the_end (choice_id, text)
VALUES (7, 'You declined the call');
INSERT INTO the_end (choice_id, text)
VALUES (8, 'You didn''t negotiate');
INSERT INTO the_end (choice_id, text)
VALUES (9, 'Your lies have been exposed');
INSERT INTO the_end (choice_id, text)
VALUES (12, 'You declined the call');

INSERT INTO to_be_continue (choice_id, step_id)
VALUES (10, 5);
INSERT INTO to_be_continue (choice_id, step_id)
VALUES (11, 6);

